/**
 * UK sensitive-site point data: prisons, police stations and MOD / military
 * sites. These are common drone no-fly / sensitivity hotspots and provide useful
 * situational context when triaging a sighting.
 *
 * Source: OpenStreetMap contributors via the Overpass API (ODbL). Generated by
 * `scripts/fetch-sensitive-sites.mjs` into `public/uk-sensitive-sites.geojson`.
 * Polygon features (e.g. prison/military estate footprints) are reduced to a
 * representative centre point. Coverage reflects OSM completeness and is for
 * situational awareness only.
 */

import type * as L from "leaflet"

export type SiteCategory = "prison" | "police" | "mod"

export interface SiteProperties {
  category: SiteCategory
  name: string | null
}

export type SiteFeature = GeoJSON.Feature<GeoJSON.Point, SiteProperties>
export type SiteCollection = GeoJSON.FeatureCollection<GeoJSON.Point, SiteProperties>

export const SITE_CATEGORY_COLOR: Record<SiteCategory, string> = {
  prison: "#a855f7", // purple
  police: "#2563eb", // blue
  mod: "#16a34a", // green
}

export const SITE_CATEGORY_LABEL: Record<SiteCategory, string> = {
  prison: "Prison",
  police: "Police station",
  mod: "MOD / military site",
}

export const SITE_CATEGORIES: SiteCategory[] = ["prison", "police", "mod"]

let cache: Promise<SiteCollection> | null = null

/** Fetch the sensitive-sites GeoJSON once and cache the promise. */
export function loadUkSensitiveSites(): Promise<SiteCollection> {
  if (!cache) {
    cache = fetch("/uk-sensitive-sites.geojson").then((r) => {
      if (!r.ok) throw new Error(`Failed to load sensitive-site data: ${r.status}`)
      return r.json() as Promise<SiteCollection>
    })
  }
  return cache
}

function tooltipHtml(p: SiteProperties): string {
  return (
    `<strong>${p.name ?? SITE_CATEGORY_LABEL[p.category]}</strong>` +
    `<br/><span style="opacity:0.8">${SITE_CATEGORY_LABEL[p.category]}</span>`
  )
}

/**
 * Build a styled Leaflet layer of sensitive-site markers. Each category is
 * rendered as a small coloured circle marker. Pass `categories` to limit which
 * site types are included.
 */
export function buildSensitiveSitesLayer(
  leaflet: typeof import("leaflet"),
  data: SiteCollection,
  categories: SiteCategory[] = SITE_CATEGORIES,
): L.GeoJSON {
  const enabled = new Set(categories)
  return leaflet.geoJSON(data as GeoJSON.GeoJsonObject, {
    filter: (feature) => {
      const props = (feature?.properties ?? {}) as SiteProperties
      return enabled.has(props.category)
    },
    pointToLayer: (feature, latlng) => {
      const props = (feature.properties ?? {}) as SiteProperties
      const color = SITE_CATEGORY_COLOR[props.category]
      return leaflet.circleMarker(latlng, {
        radius: 5,
        color: "#0b1220",
        weight: 1,
        opacity: 0.9,
        fillColor: color,
        fillOpacity: 0.9,
      })
    },
    onEachFeature: (feature, layer) => {
      const props = (feature.properties ?? {}) as SiteProperties
      layer.bindTooltip(tooltipHtml(props), { sticky: true, direction: "top" })
    },
  })
}
